/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.ControladorClient;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * @author Jean Carlo Massami Yamada
 *
 * Aplicação desenvolvida como trabalho final da disiciplina de Computação Distrubuida ministrada 
 * por Dr.Prof. Milton Hirokazu Shimabukuro do curso de Ciências da Computação da 
 * UNESP(Universidade Estadual Paulista) "Júlio Mesquita Filho" - Câmpus de Presidente Prudente.
 * Com o intuito de concretizar o aprendizado da matéria, o bjetivo da aplicação é ter
 * um servidor que irá invocar métodos remotos (RMI (Remote Method Invocation))
 * para atender requisições de seus clientes conectados via TCP.
 */
/**
 *  * @author Jean Carlo Massami Yamada
 *
 * Classe ClientGui, a qual é responsavel pela interface gráfica.
 * Como foi utlizado a IDE NetBeans, vários recursos são construido automaticamente.
 */

public class ClientGui extends javax.swing.JFrame {

    /**
     * Creates new form ClientGui
     */
    public ClientGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOperation = new javax.swing.ButtonGroup();
        jLabelIp = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jFormattedTextFieldPort = new javax.swing.JFormattedTextField();
        jTextFieldIp = new javax.swing.JTextField();
        jButtonConnect = new javax.swing.JButton();
        jScrollPaneOp = new javax.swing.JScrollPane();
        jPanelOp = new javax.swing.JPanel();
        jFormattedTextFieldN1 = new javax.swing.JFormattedTextField();
        jLabelN1 = new javax.swing.JLabel();
        jFormattedTextFieldN2 = new javax.swing.JFormattedTextField();
        jLabelN2 = new javax.swing.JLabel();
        jRadioButtonSum = new javax.swing.JRadioButton();
        jRadioButtonSub = new javax.swing.JRadioButton();
        jRadioButtonDiv = new javax.swing.JRadioButton();
        jRadioButtonMult = new javax.swing.JRadioButton();
        jButtonStart = new javax.swing.JButton();
        jFormattedTextFieldResult = new javax.swing.JFormattedTextField();
        jLabelResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaClient = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButtonConnectDisconnect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabelIp.setText("IP");

        jLabelPort.setText("Porta");

        jFormattedTextFieldPort.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jTextFieldIp.setText("127.0.0.1");

        jButtonConnect.setText("conectar");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jPanelOp.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelN1.setText("Número 1");

        jLabelN2.setText("Número 2");

        buttonGroupOperation.add(jRadioButtonSum);
        jRadioButtonSum.setText("somar");

        buttonGroupOperation.add(jRadioButtonSub);
        jRadioButtonSub.setText("subtrair");

        buttonGroupOperation.add(jRadioButtonDiv);
        jRadioButtonDiv.setText("dividir");

        buttonGroupOperation.add(jRadioButtonMult);
        jRadioButtonMult.setText("multiplicar");

        jButtonStart.setText("enviar");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jFormattedTextFieldResult.setEditable(false);

        jLabelResult.setText("Resultado");

        jTextAreaClient.setEditable(false);
        jTextAreaClient.setColumns(20);
        jTextAreaClient.setRows(5);
        jScrollPane1.setViewportView(jTextAreaClient);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.jpeg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpLayout = new javax.swing.GroupLayout(jPanelOp);
        jPanelOp.setLayout(jPanelOpLayout);
        jPanelOpLayout.setHorizontalGroup(
            jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOpLayout.createSequentialGroup()
                        .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelOpLayout.createSequentialGroup()
                                .addComponent(jLabelResult)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldResult))
                            .addGroup(jPanelOpLayout.createSequentialGroup()
                                .addComponent(jLabelN1)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldN1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelOpLayout.createSequentialGroup()
                                .addComponent(jLabelN2)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldN2))
                            .addGroup(jPanelOpLayout.createSequentialGroup()
                                .addComponent(jButtonStart)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(151, 151, 151)
                        .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSum)
                            .addComponent(jRadioButtonSub)
                            .addComponent(jRadioButtonMult)
                            .addComponent(jRadioButtonDiv))))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanelOpLayout.setVerticalGroup(
            jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpLayout.createSequentialGroup()
                        .addComponent(jRadioButtonSum)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonSub))
                    .addGroup(jPanelOpLayout.createSequentialGroup()
                        .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelN1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelN2)
                            .addComponent(jFormattedTextFieldN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpLayout.createSequentialGroup()
                        .addComponent(jRadioButtonMult)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDiv))
                    .addGroup(jPanelOpLayout.createSequentialGroup()
                        .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResult)
                            .addComponent(jFormattedTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStart)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jScrollPaneOp.setViewportView(jPanelOp);

        jButtonConnectDisconnect.setText("desconectar");
        jButtonConnectDisconnect.setEnabled(false);
        jButtonConnectDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectDisconnectActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.jpeg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa.jpeg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneOp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPort)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonConnect)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIp)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonConnectDisconnect, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIp)
                        .addComponent(jTextFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPort)
                        .addComponent(jFormattedTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonConnect)
                            .addComponent(jButtonConnectDisconnect)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneOp, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*método que requisita a conexão com um servidor após presionado o botão connect*/
    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        // TODO add your handling code here:

        /*apenas verifica se as caixas de texto estão devidamente preenchidas*/
        if (!jTextFieldIp.getText().isEmpty()) {
            ControladorClient.setIp(jTextFieldIp.getText());
        } else {
            return;
        }

        String port = jFormattedTextFieldPort.getText();
        try {
            ControladorClient.setServerPort(Integer.parseInt(port));
        } catch (NumberFormatException ex) {
            System.err.println(ex);
            return;
        }

        /*requisita a conexão com o servidor*/
        if (ControladorClient.connect()) {

            jButtonConnectDisconnect.setEnabled(true);
            jTextFieldIp.setEnabled(false);
            jFormattedTextFieldPort.setEnabled(false);
            jButtonConnect.setEnabled(false);
        }

    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonConnectDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectDisconnectActionPerformed
        // TODO add your handling code here:
        if (ControladorClient.disconnect()) {

            jButtonConnectDisconnect.setEnabled(false);
            jButtonConnect.setEnabled(true);
            jTextFieldIp.setEnabled(true);
            jFormattedTextFieldPort.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonConnectDisconnectActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        String operation = null;

        if (!jFormattedTextFieldN1.getText().isEmpty()) {
            operation = jFormattedTextFieldN1.getText() + " ";
        }
        if (!jFormattedTextFieldN2.getText().isEmpty()) {
            operation += jFormattedTextFieldN2.getText() + " ";
        }

        if (jRadioButtonDiv.isSelected()) {
            operation += "div";
        }
        if (jRadioButtonMult.isSelected()) {
            operation += "mult";
        }
        if (jRadioButtonSub.isSelected()) {
            operation += "sub";
        }
        if (jRadioButtonSum.isSelected()) {
            operation += "sum";
        }

        ControladorClient.start(operation);
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"        try {\n" +
"            /*requisitando conexão com um servidor*/\n" +
"            socket = new Socket(InetAddress.getByName(ip), port);\n" +
"            \n" +
"            /*instanciando objetos de entrada e saída do socket*/\n" +
"            dataInputStream = new DataInputStream(socket.getInputStream());\n" +
"            dataOutputStream = new DataOutputStream(socket.getOutputStream());\n" +
"            \n" +
"            return true;\n" +
"        }");
    }//GEN-LAST:event_formMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"        try {\n" +
"            \n" +
"            /*enviando dados*/\n" +
"            dataOutputStream.writeUTF(operation);\n" +
"            \n" +
"            /*recebendo dados*/\n" +
"            String data = dataInputStream.readUTF();	    \n" +
"            System.out.println(data);\n" +
"            \n" +
"            /*inserindo resultado na interface gráfca*/\n" +
"            ControladorClientGui.getjFormattedTextFieldResult().setText(data);\n" +
"            return true;\n" +
"        } ");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"try {\n" +
"            /*encerrando conexão com o servidor*/\n" +
"            socket.close();\n" +
"            return true;\n" +
"        }");
    }//GEN-LAST:event_jLabel3MouseClicked

    public ButtonGroup getButtonGroup1() {
        return buttonGroupOperation;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroupOperation = buttonGroup1;
    }

    public JButton getjButtonConnect() {
        return jButtonConnect;
    }

    public void setjButtonConnect(JButton jButtonConnect) {
        this.jButtonConnect = jButtonConnect;
    }

    public JButton getjButtonConnectDisconnect() {
        return jButtonConnectDisconnect;
    }

    public void setjButtonConnectDisconnect(JButton jButtonConnectDisconnect) {
        this.jButtonConnectDisconnect = jButtonConnectDisconnect;
    }

    public JButton getjButtonStart() {
        return jButtonStart;
    }

    public void setjButtonStart(JButton jButtonStart) {
        this.jButtonStart = jButtonStart;
    }

    public JFormattedTextField getjFormattedTextFieldN1() {
        return jFormattedTextFieldN1;
    }

    public void setjFormattedTextFieldN1(JFormattedTextField jFormattedTextFieldN1) {
        this.jFormattedTextFieldN1 = jFormattedTextFieldN1;
    }

    public JFormattedTextField getjFormattedTextFieldN2() {
        return jFormattedTextFieldN2;
    }

    public void setjFormattedTextFieldN2(JFormattedTextField jFormattedTextFieldN2) {
        this.jFormattedTextFieldN2 = jFormattedTextFieldN2;
    }

    public JFormattedTextField getjFormattedTextFieldPort() {
        return jFormattedTextFieldPort;
    }

    public void setjFormattedTextFieldPort(JFormattedTextField jFormattedTextFieldPort) {
        this.jFormattedTextFieldPort = jFormattedTextFieldPort;
    }

    public JFormattedTextField getjFormattedTextFieldResult() {
        return jFormattedTextFieldResult;
    }

    public void setjFormattedTextFieldResult(JFormattedTextField jFormattedTextFieldResult) {
        this.jFormattedTextFieldResult = jFormattedTextFieldResult;
    }

    public JLabel getjLabelIp() {
        return jLabelIp;
    }

    public void setjLabelIp(JLabel jLabelIp) {
        this.jLabelIp = jLabelIp;
    }

    public JLabel getjLabelN1() {
        return jLabelN1;
    }

    public void setjLabelN1(JLabel jLabelN1) {
        this.jLabelN1 = jLabelN1;
    }

    public JLabel getjLabelN2() {
        return jLabelN2;
    }

    public void setjLabelN2(JLabel jLabelN2) {
        this.jLabelN2 = jLabelN2;
    }

    public JLabel getjLabelPort() {
        return jLabelPort;
    }

    public void setjLabelPort(JLabel jLabelPort) {
        this.jLabelPort = jLabelPort;
    }

    public JLabel getjLabelResult() {
        return jLabelResult;
    }

    public void setjLabelResult(JLabel jLabelResult) {
        this.jLabelResult = jLabelResult;
    }

    public JPanel getjPanelOp() {
        return jPanelOp;
    }

    public void setjPanelOp(JPanel jPanelOp) {
        this.jPanelOp = jPanelOp;
    }

    public JRadioButton getjRadioButtonDiv() {
        return jRadioButtonDiv;
    }

    public void setjRadioButtonDiv(JRadioButton jRadioButtonDiv) {
        this.jRadioButtonDiv = jRadioButtonDiv;
    }

    public JRadioButton getjRadioButtonMult() {
        return jRadioButtonMult;
    }

    public void setjRadioButtonMult(JRadioButton jRadioButtonMult) {
        this.jRadioButtonMult = jRadioButtonMult;
    }

    public JRadioButton getjRadioButtonSub() {
        return jRadioButtonSub;
    }

    public void setjRadioButtonSub(JRadioButton jRadioButtonSub) {
        this.jRadioButtonSub = jRadioButtonSub;
    }

    public JRadioButton getjRadioButtonSum() {
        return jRadioButtonSum;
    }

    public void setjRadioButtonSum(JRadioButton jRadioButtonSum) {
        this.jRadioButtonSum = jRadioButtonSum;
    }

    public JScrollPane getjScrollPaneOp() {
        return jScrollPaneOp;
    }

    public void setjScrollPaneOp(JScrollPane jScrollPaneOp) {
        this.jScrollPaneOp = jScrollPaneOp;
    }

    public JTextField getjTextFieldIp() {
        return jTextFieldIp;
    }

    public void setjTextFieldIp(JTextField jTextFieldIp) {
        this.jTextFieldIp = jTextFieldIp;
    }

    public ButtonGroup getButtonGroupOperation() {
        return buttonGroupOperation;
    }

    public void setButtonGroupOperation(ButtonGroup buttonGroupOperation) {
        this.buttonGroupOperation = buttonGroupOperation;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getjTextAreaClient() {
        return jTextAreaClient;
    }

    public void setjTextAreaClient(JTextArea jTextAreaClient) {
        this.jTextAreaClient = jTextAreaClient;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOperation;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonConnectDisconnect;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JFormattedTextField jFormattedTextFieldN1;
    private javax.swing.JFormattedTextField jFormattedTextFieldN2;
    private javax.swing.JFormattedTextField jFormattedTextFieldPort;
    private javax.swing.JFormattedTextField jFormattedTextFieldResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIp;
    private javax.swing.JLabel jLabelN1;
    private javax.swing.JLabel jLabelN2;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JPanel jPanelOp;
    private javax.swing.JRadioButton jRadioButtonDiv;
    private javax.swing.JRadioButton jRadioButtonMult;
    private javax.swing.JRadioButton jRadioButtonSub;
    private javax.swing.JRadioButton jRadioButtonSum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneOp;
    private javax.swing.JTextArea jTextAreaClient;
    private javax.swing.JTextField jTextFieldIp;
    // End of variables declaration//GEN-END:variables
}
